### ISSUE TITLE
`ema align` command

### ISSUE THREAD

**Issue by vladsaveliev** [arshajii/ema#12]
Hi,

Not clear how to run `ema align` from the preproc-generated directory (called `output_dir` in the documentation). The example doesn't mention this directory, and not clear where `parallel` is taking the input parameters for `-s {}` - nothing is passed with `:::`:

```
parallel --bar -j10 "ema align -t 4 -d -r /path/to/ref.fa -s {} | samtools sort -@ 4 -O bam -l 0 -m 4G -o {}.bam -"
```

**Comment by arshajii** [comment]
Thanks -- we've just fixed this in the README:

```bash
parallel --bar -j10 "ema align -t 4 -d -r /path/to/ref.fa -s {} |\
  samtools sort -@ 4 -O bam -l 0 -m 4G -o {}.bam -" ::: output_dir/ema-bin-???
```

We also updated the no-barcode bin to be called "ema-nobc" (rather than "ema-bin-nobc"). This is updated in the README as well, so if you already did preprocessing you could just `mv output_dir/ema-bin-nobc output_dir/ema-nobc`.

**Comment by vladsaveliev** [comment]
Cool, thanks for fixing!
