### ISSUE TITLE
Read length requirements, and error handling

### ISSUE THREAD

**Issue by vladsaveliev** [arshajii/ema#13]
Running `ema count` on an output from the sequencer, it returns with non-zero without any message, leaving empty `*.ema-fcnt` and `*.ema-ncnt` files. Figured that it failed when running into this read:

```
@A00130:39:H5GWHDMXX:1:1101:8919:3192 1:N:0:TATGATTC
GTCGTAACATC
+
FFFFFFFFFFF
```

Does it have to do with the read length? Are there are minimal requirements? And can it be handled with the script - with error message of built-in filtering?

**Comment by vladsaveliev** [comment]
By the way, it would be nice if EMA could be run directly from the output of demultiplexing. A sample is usually split into 4 .fastq.gz pairs per lane (https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/bcl2fastq-direct), so the folder, for instance, look like this:

```
Sample_S13_L001_I1_001.fastq.gz  Sample_S13_L002_R1_001.fastq.gz  Sample_S14_L001_R2_001.fastq.gz  Sample_S15_L001_I1_001.fastq.gz  Sample_S15_L002_R1_001.fastq.gz  Sample_S16_L001_R2_001.fastq.gz
Sample_S13_L001_R1_001.fastq.gz  Sample_S13_L002_R2_001.fastq.gz  Sample_S14_L002_I1_001.fastq.gz  Sample_S15_L001_R1_001.fastq.gz  Sample_S15_L002_R2_001.fastq.gz  Sample_S16_L002_I1_001.fastq.gz
Sample_S13_L001_R2_001.fastq.gz  Sample_S14_L001_I1_001.fastq.gz  Sample_S14_L002_R1_001.fastq.gz  Sample_S15_L001_R2_001.fastq.gz  Sample_S16_L001_I1_001.fastq.gz  Sample_S16_L002_R1_001.fastq.gz
Sample_S13_L002_I1_001.fastq.gz  Sample_S14_L001_R1_001.fastq.gz  Sample_S14_L002_R2_001.fastq.gz  Sample_S15_L002_I1_001.fastq.gz  Sample_S16_L001_R1_001.fastq.gz  Sample_S16_L002_R2_001.fastq.gz```

Currently I'm merging them into a single interleaved file with:

```
for fp in *L001_R1_001.fastq.gz
do
	paste <(pigz -c -d $fp | paste - - - -) <(pigz -c -d ${fp/_R1_/_R2_} | paste - - - -) | tr "\t" "\n" >> Sample.fastq
done
```

**Comment by inumanag** [comment]
As specified in README, do not include index *_I1_* files in the count / correct / mapping stage, since they are useless and make all sorts of issues (as you experienced :) ).

Also, there is a helper command there for demultiplexed files:
```
parallel -j40 --bar 'paste <(pigz -c -d {} | paste - - - -) <(pigz -c -d {= s:_R1_:_R2_: =} | paste - - - -) | tr "\t" "\n" |\
  ema count -w /path/to/whitelist.txt -o {/.} 2>{/.}.log' ::: *_R1_*.gz
``` 

(more details are in the README). 

If it still doesn't work please let us know :)

**Comment by inumanag** [comment]
And there is no need to merge fastqs --- counting is actually faster if you can run parallel on small chunks.

**Comment by vladsaveliev** [comment]
I don't include `_I1` - that read is from `_R1`

**Comment by vladsaveliev** [comment]
`ema count` in a parallel wrapper doesn't work for some reason - getting `Quality score less than 33---exiting!`. Trying to figure out if that's I'm doing something wrong...

**Comment by vladsaveliev** [comment]
Ah, the `awk` bit doesn't work inside a `parallel` command:

Doesn't work:

```
parallel -j32 --bar 'paste <(pigz -c -d {} | paste - - - - | awk -F "\t" "length($2) >= 40") <(pigz -c -d {= s:_R1_:_R2_: =} | paste - - - - | awk -F "\t" "length($2) >= 40") | tr "\t" "\n" | ema count -w 4M-with-alts-february-2016.txt -o {/.} 2>{/.}.log' ::: Colo829_80pc_S14_L001_R1_001.fastq.gz
```

Does work:

```
paste <(pigz -c -d Colo829_80pc_S14_L001_R1_001.fastq.gz | paste - - - - | awk -F '\t' 'length($2) > 40') <(pigz -c -d Colo829_80pc_S14_L001_R2_001.fastq.gz | paste - - - - | awk -F '\t' 'length($2) > 40') | tr '\t' '\n' | ema count -w 4M-with-alts-february-2016.txt -o tmp
```

**Comment by inumanag** [comment]
Minimum quality score should be 33 (#) on all 10X data.
I guess the reason it fails is that you encounter those short adapter reads which do not follow the normal rules, although it's really weird that they are not in index _I1_ files (I never seen R1 file having them before). I will push an update to support those (and ignore) ASAP, so that you can ignore awk.

**Comment by vladsaveliev** [comment]
The read length in `R1` might vary, with possible some short outliers. So good to handle such rare cases in preprocessing. Thanks so much for doing that!

**Comment by inumanag** [comment]
Hi Vlad,
just committed a new branch (`testing`) which has the required changes. Namely, it will ignore any read which is not long enough (less than 32bp) or which has weird quality scores (i.e. qs < 32). It should support variable read lengths: however, be aware that we already do trim reads (barcode and next 7bp of the read) and that you might end up trimming read twice. Please let me know if it works now.

**Comment by vladsaveliev** [comment]
Thanks so much! I will give it a try now. 

It's not barcode trimming - it's adapter trimming, a different thing :)

**Comment by vladsaveliev** [comment]
Works great, the results look correct. Thank you a lot for the help and addressing the issue so quickly! I'll be doing more evaluation later but I think this one can be resolved - unless you want to keep it open until you merge into master.
