### ISSUE TITLE
Homebrew / Linuxbrew package of ema

### ISSUE THREAD

**Issue by sjackman** [arshajii/ema#17]
I've created a Homebrew / Linuxbrew package for EMA.
See https://github.com/brewsci/homebrew-bio/pull/208
First install Homebrew on macOS or Linuxbrew on Linux, then run…
```sh
brew install brewsci/bio/ema
```
Would you like to update this formula with new releases of EMA? To update the formula, open a pull request that updates the `tag` and `revision`.
See https://github.com/brewsci/homebrew-bio/blob/master/Formula/ema.rb

**Comment by arshajii** [comment]
Thanks! We just did a preprocessing fix that I'll release soon, and I'll be sure to update that formula.

**Comment by arshajii** [comment]
I just opened a pull request for the new 6.0.1 release, and added this install option to the README. I'll close this issue for now; thanks again for your help.

**Comment by sjackman** [comment]
Happy to help!
