### ISSUE TITLE
Replace XC with MI ?

### ISSUE THREAD

**Issue by sjackman** [arshajii/ema#20]
If the cloud identifier `XC` is compatible with `MI:i`, could `MI:i` be used instead, for compatibility with Lariat?

**Comment by arshajii** [comment]
I think it should be compatible. I just want to make sure that Long Ranger's `MI`s aren't somehow unique even between different runs of Lariat. I don't think it should matter that much anyway because the (barcode `MI`) pair should be unique regardless.

**Comment by sjackman** [comment]
I believe `MI` are serially incrementing integers starting at 0.

**Comment by arshajii** [comment]
OK we're now using `MI` instead of `XC`.

**Comment by sjackman** [comment]
Thanks!
