### ISSUE TITLE
Reads mapping to N's in the beginning of a chromosome with 1000genomes BWA indices

### ISSUE THREAD

**Issue by vladsaveliev** [arshajii/ema#22]
There is an odd behaviour we encountered for EMA aligning against the hg38 reference genome. For some reason many reads appear to map to the N stretch in a beginning of a chromosome. Below is an IGV screenshot of the region chr5:1-15000, from top to bottom - EMA GRCh37, EMA hg38, Longranger GRCh37, and Longranger hg38:

<img width="1680" alt="screen shot 2018-07-20 at 20 20 00" src="https://user-images.githubusercontent.com/1575412/42997668-e3094c5a-8c5a-11e8-93bf-7f56e2971e3c.png">

Reads are colored by the BX tag (bleak colors) and mismatches (bright colors). As you can see, in the rightmost part (it's the telomeric repeat region) EMA reads map to hg38 with tons of mismatches, basically most of the bases are wrong and the average MAPQ is as low as 3. Bust the most odd thing for us is that so many reads are mapped to the leftmost part: the first 10k of chr5 on both reference genomes are just stretches of `N`. 

All 4 BAMs are generated from the same read set. GRCh37 is a non-decoy version (does not have the hs37d5 contig). The EMA version is 0.6.1.

We are wondering why such mapping can be happening? If that can of help, we sliced the chr5:1-15000 regions from all 4 BAM files and uploaded in a tarball: https://drive.google.com/file/d/1o2mrzkS0qt2L98-3cY5y5RFalpWwsmVF/view?usp=sharing

Happy to share other data if that can be helpful!

cc @brainstorm and @ohofmann

Vlad

**Comment by arshajii** [comment]
Let me look into this. In the meantime I wonder if this is a result of the fragment density optimization that EMA does. Are you running with ‘-d’? If so what happens if you run without it?

**Comment by vladsaveliev** [comment]
Hi,

Yes, I'm using `-d` as per the examples in the README `https://github.com/arshajii/ema#mapping`

Will run it w/o `-d`, but the full rerun will take 2-3 days.

Thanks for looking into it!

**Comment by vladsaveliev** [comment]
Finished rerunning without the `-d` option, but still the same picture:

<img width="1680" alt="screen shot 2018-07-21 at 16 42 54" src="https://user-images.githubusercontent.com/1575412/43032981-243891ae-8d05-11e8-821d-8845bf0d7ea5.png">

**Comment by arshajii** [comment]
Looking at this now. Just to be clear, it's only the hg38 mappings that look strange like this? All hg19 results look OK?

If that's the case my first thought would be it's some indexing bug that for some reason only happens on hg38 (which by the way I haven't tested). I'll try doing some hg38 tests to track down the issue.

**Comment by arshajii** [comment]
If at all possible, could you please send me the FASTQ records of one of the offending barcodes? You should be able to just grep for the barcode in EMA's preprocessed FASTQs.

Also are you using 10x's prepackaged hg38 reference?

**Comment by vladsaveliev** [comment]
Hi, thanks so much for looking!

Yep, only hg38 looks strange. I'm not using the 10x pre-packaged references, but rather the reference files that came with my bcbio-nextgen installation. So that's a good point on possibility of corrupt indices. To make sure, I'm gonna now re-align offending reads to the 10x pre-prepackaged bundle, and will let you know how it goes.

One of the offending barcodes: GACAACTAGGAGGACG. I've just picked it from the BAM file slice that I shared in a message above. The BAMs store the barcodes in BX and RX tags. Or do you think if I find that read in the FASTQs, it will make a difference?

Vlad

**Comment by vladsaveliev** [comment]
So I tried to rerun with the reference bundle downloaded from the 10x website. Also I ran with another version of bcbio-nextgen reference bundle (which was automatically retrieved from the 1000 genomes website http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/),  to make sure the previous one wasn't just corrupted. 

Indeed, it's completely different alignment with the 10x bundle, no more mapping to N's and tons of mismatches:

![screen shot 2018-07-29 at 16 38 55](https://user-images.githubusercontent.com/1575412/43363766-620865ae-934f-11e8-846b-88f65393438d.png)

![screen shot 2018-07-29 at 16 57 06](https://user-images.githubusercontent.com/1575412/43363822-a4d15a70-9350-11e8-91bd-15fdbc8fa97a.png)

But I don't understand why it should be different. Does 10x do anything specific to build their indices? Do you know if they use some specific options or custom tools for that?

Vlad

**Comment by arshajii** [comment]
Hmm that's odd. As far as I know they don't do anything special other than prepackage all the indices beforehand. Beyond that, EMA doesn't rely on anything except the fai and BWA index files. I'm downloading the reference files you linked above to see if I can replicate/find the issue; will keep you posted.

**Comment by arshajii** [comment]
OK I've figured out the issue here. Basically EMA uses an 8-bit integer to keep track of the index of the chromosome (given by the fai file). But that 1000 Genomes reference has far more than 2<sup>8</sup> contigs, so some indices are wrapping around and showing up in the output as an incorrect contig (chr5 in your case). I've fixed this by swapping to a 32-bit integer to store contig indices, and it looks like all is well now.

Let me know if things look good on your end with the latest version from Github. If so, I'll make a new release of EMA including this fix.

**Comment by ohofmann** [comment]
Nice forensics -- thanks for following up!

**Comment by vladsaveliev** [comment]
@arshajii, totally makes sense now! Thanks for identifying and fixing the issue!

I ran the fixed version with the one of the offending reads - and it correctly maps it to one of the decoy chromosomes now. So I guess it's all good with this issue. Looking forward to a new release!

Thanks again for resolving this so quickly!

Vlad
