### ISSUE TITLE
10x bamtofastq with EMA BAM

### ISSUE THREAD

**Issue by vladsaveliev** [arshajii/ema#23]
Hi,

A side feature request popped up while exploring the hg38 alignments peculiarities. 

I tired to use this tool to convert a portion of EMA BAM file back to barcoded FASTQ: https://support.10xgenomics.com/docs/bamtofastq But the tool reported it as "Unrecognized 10x BAM file.". I guess it's likely that the tool is too tied to Lariat specificities. But it would be fantastic if EMA BAMs were compatible with this tool. Not sure if it's feasible without the modifications of the tool. 

Or maybe there are alternatives that you could suggest?

Vlad

**Comment by sjackman** [comment]
I use `samtools fastq -TBX` to convert a BAM file with `BX:Z` tags to FASTQ with `BX:Z` tags.

**Comment by vladsaveliev** [comment]
Thanks Shaun, that should work I guess since EMA started to support `BX:Z`-tagged FASTQs

**Comment by sjackman** [comment]
No worries, Vlad. Happy to help.
