### ISSUE TITLE
BWA incompatible alignment SAM flags

### ISSUE THREAD

**Issue by mcieslik-mctp** [arshajii/ema#3]
I was trying to use the ema-aligned BAM file for downstream structural-variant discovery. I noticed that extraction of split/discordant reads (using https://github.com/hall-lab/extract_sv_reads) resulted in no split/discordant reads being discovered. At least part of the reason is the non-standard use of alignment flags by ema. For example, whereas BWA may align a read with flag 113:

```
    read paired (0x1)
    read reverse strand (0x10)
    mate reverse strand (0x20)
    first in pair (0x40)
```

EMA will align the same read pair with flag 115
```
    read paired (0x1)
    read mapped in proper pair (0x2)
    read reverse strand (0x10)
    mate reverse strand (0x20)
    first in pair (0x40)
```
For Illumina chemistry the rev-rev orientation is not a proper pair. In many cases the "proper" reads are aligned to different chromosomes...

**Comment by arshajii** [comment]
Yeah, this flag is currently being set in cases when it shouldn't (it's set in the code [here](https://github.com/arshajii/ema/blob/master/src/samrecord.c#L155)). This should be pretty straightforward to fix; just need to check if both mates are mapped nearby and are oriented correctly. I'll fix this shortly!

**Comment by arshajii** [comment]
OK I just implemented the proper-mates check. The flags _should_ be fixed now, but let me know if you run into any more issues.

**Comment by arshajii** [comment]
Closing for now, but let me know if anything else doesn't work.

**Comment by mcieslik-mctp** [comment]
Thanks, I still think there is an issue with split reads i.e. reads with supplemental alignments, but I have not yet tracked down what the exact flag-difference is.

**Comment by arshajii** [comment]
Okay -- If you happen to find any examples with strange flags you could post them here an I could look into them. Also, it's just the flags? The alignments themselves are fine?
