### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by MaestSi** [arshajii/ema#32]
Dear ema developers,
after having a core dump error with the `ema preproc` pipeline, using the conda installed version, I followed the suggestions given in Issue #27 and tried to build from source.
However, `make` instruction gave this error:

> make[1]: Leaving directory '/home/simone/software/ema/bwa'
> g++ -lstdc++ -march=native -O3 -flto -fopenmp -lpthread  obj/split.o  obj/align.o  obj/barcodes.o  obj/bwabridge.o  obj/techs.o  obj/samrecord.o  obj/main.o  obj/util.o  obj/samdict.o  cpp/main.o  cpp/count.o  cpp/format.o  cpp/correct.o -Lbwa -lbwa -lm -lz -lpthread -o ema
> lto1: fatal error: bytecode stream in file ‘obj/split.o’ generated with LTO version 3.0 instead of the expected 6.0
> compilation terminated.
> lto-wrapper: fatal error: g++ returned 1 exit status
> compilation terminated.
> /usr/bin/ld: error: lto-wrapper failed
> collect2: error: ld returned 1 exit status
> Makefile:41: recipe for target 'ema' failed
> make: *** [ema] Error 1
 
How do you think I could solve this? Are there some requirements on the compiler version?
Thanks,
Simone

**Comment by arshajii** [comment]
Hi,
What gcc/g++ versions are you using? EMA has both C++ and C components, so I wonder if there's some weird incompatibility between gcc and g++ here. Also, ideally we can just fix the conda version so that it works on your system. What system are you on? Is it 32-bit by chance?

**Comment by MaestSi** [comment]
Hi,
I was able to fix the issue installing gcc and g++ compilers with `conda install -c anaconda gcc` , since the versions of gcc and g++ that were installed in my system were not the same and probably that caused the issue. Thank you! By the way, my system is 64 bit.
Simone
