### ISSUE TITLE
How to use "-b" flag?

### ISSUE THREAD

**Issue by andreaswallberg** [arshajii/ema#34]
Dear developers,

I have read all discussion/issues related to "BX:Z" and tried to generate new fastq files by adding the -b flag to my "ema preproc" run:

-b: output BX:Z-formatted FASTQs [off]

However, as far as I can tell it does not actually print new fastq files anywhere in the file system. I get my 500 bins and downstream alignment works just fine but despite inspecting the source code, I simply can't figure out how the "-b" flag works.

Does it take any extra parameters or is it simply a boolean on/off?
Is it supposed to print to STDOUT or a new file?

Grateful for feedback on this!
Cheers!

**Comment by arshajii** [comment]
Hi,
Could you post some lines from one of the bins? Are these not BX:Z-formatted after using `-b`?

**Comment by andreaswallberg** [comment]
Hi!

I deleted the bins and reran the exact same commands. It has now printed the expected fastq-formatted output, with the BX:Z tag in the headers. Not sure what went wrong before. Sorry for the confusion.
